"use strict";

module.exports = {
    CLOSE: "Close",
    EDIT: "Edit",
    COPY: "Copy",
    FILE: "File",
    DELETE: "Delete",
    REMOVE: "Remove",
    NONE: "(None)",
    GENERATE: "Generate",
    CURRENT: "Current",
    CANCEL: "Cancel",
    OK: "Ok",
    BACK: "Back",
    TAGS: "Tags",
    ADD: "Add",
    ADD_TAG: "Add tag",
    OPEN: "Open",
    SAVE: "Save",
    ABOUT: "About",
    ABOUT_SOMETHING: "About %",
    SAVE_TO: "Save to",
    CREATE: "Create",
    FILE_TOO_BIG: "File too big.",
    PROTECT: "Protect",
    CREATE_ENTRY: "Entry",
    NO_PASSWORD: "No password",
    CRACK_TIME: "Guessable in %",
    CREATE_TAG: "Tag",
    UNTITLED_TAG: "Untitled tag",
    UNTITLED_ENTRY: "Untitled entry",
    BAD_FILE_FORMAT: "Bad file format",
    SET_MASTER_PASSWORD: "Set master password",
    CREATE_EMPTY_FILE: "Create empty file",
    ENTER_NAME_OF_ITEM: "Please pick name of new item",
    OPENING_FILE_NEED_PASS: "File \u201C%\u201D is encrypted, please enter password",
    ERROR_OPENING_FILE: "Error opening file",
    FILE_NAME_NEW: "Name of new password file",
    FILE_NAME_SAVE_AS: "Please enter file name",
    MASTER_PASSWORD_NEW: "Pick a strong master password and do not lose it",
    MASTER_PASSWORD_ENTRY: "Enter your password to continue",
    MASTER_PASSWORD_CHANGE: "Pick a new password and do not lose it",
    ABOUT_INTRO: "% is web password manager which does not own your passwords "+
        "so it cannot steal your passwords!",
    THANKS_TO: "Many thanks go to:",
    GOOGLE_INTEGRAGE: "Add to Drive",
    GOOGLE_DRIVE: "Google Drive\u2122",
    GOOGLE_OPEN: "Open",
    GOOGLE_SAVE: "Save",
    GOOGLE_SAVE_AS: "Save as",
    LOCAL_SAVE: "Download a copy",
    LOCAL_OPEN: "Open"
};
